### ISSUE TITLE
按ss面板教程装的，但是运行sever.py时报错

### ISSUE THREAD

**Issue by startwish** [Ehco1996/shadowsocksr#1]
这个是报错的内容
IPv6 support
Traceback (most recent call last):
  File "server.py", line 74, in <module>
    main()
  File "server.py", line 54, in main
    if get_config().API_INTERFACE == 'mudbjson':
AttributeError: 'NoneType' object has no attribute 'API_INTERFACE'

**Comment by Ehco1996** [comment]
如果Python版本小于2.7 请升级
