### ISSUE TITLE
出现错误无法执行！

### ISSUE THREAD

**Issue by a1437272595** [Ehco1996/shadowsocksr#13]
IPv6 support
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from transfer import web_transfer, db_transfer
  File "/home/shadowsocksr/transfer/web_transfer.py", line 15, in <module>
    from utils.web_tools import EhcoApi
  File "/home/shadowsocksr/utils/web_tools.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
报错就是这个了...求作者大大解答下

**Comment by arrayJY** [comment]
pip install -r requirements.txt
之后再运行
