### ISSUE TITLE
前段能用，但是后端不知道为什么报错了。。

### ISSUE THREAD

**Issue by zihexue** [Ehco1996/shadowsocksr#2]
大佬好，请教一下这个问题。。
报错如下：
2018-03-07 20:00:37 ERROR    web_transfer.py:52 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 35, in getApi
    res = self.session_pool.get(url, params=payload, timeout=10)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

2018-03-07 20:00:37 ERROR    web_transfer.py:459 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 441, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/web_transfer.py", line 323, in pull_db_all_user
    nodeinfo = api.getApi('/nodes/{}'.format(node_id))
  File "/root/shadowsocksr/web_transfer.py", line 53, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

2018-03-07 20:01:37 INFO     connectionpool.py:203 Starting new HTTP connection (1): 127.0.0.1
2018-03-07 20:01:37 ERROR    web_transfer.py:52 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 35, in getApi
    res = self.session_pool.get(url, params=payload, timeout=10)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

2018-03-07 20:01:37 ERROR    web_transfer.py:459 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 441, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/web_transfer.py", line 323, in pull_db_all_user
    nodeinfo = api.getApi('/nodes/{}'.format(node_id))
  File "/root/shadowsocksr/web_transfer.py", line 53, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

**Comment by Ehco1996** [comment]
后端要在 前端跑起来的情况下才能读取到数据

**Comment by cheunyu** [comment]
我也是这个错误...已经对接成功，可以正常使用。后台不停的报这个错
