### ISSUE TITLE
使用python server.py能成功但是使用./run.sh等等命令就无效是为什么呢

### ISSUE THREAD

**Issue by kelekexiao123** [Ehco1996/shadowsocksr#3]
pyrhon server.py执行后显示
![image](https://user-images.githubusercontent.com/17807197/37580289-e44eb7b4-2b7d-11e8-8ef2-c70242d6954c.png)
然后是能够连上的，
执行./run.sh都是正常的，没报错，但是就是连不上了。
对shell这块不是很会，不知道哪里配置错了。

**Comment by kelekexiao123** [comment]
嗯好像tail.sh报错了

![image](https://user-images.githubusercontent.com/17807197/37581045-bc14a142-2b81-11e8-9fe4-22d5effff5f6.png)

刚刚我看了一下文档自己试着写了一行nohup好像也是可以连上的：
nohup python server.py m>> mynohup.out 2>&1 &

**Comment by Ehco1996** [comment]
系统里需要安装pip 和 requests依赖

**Comment by hansonfang** [comment]
`pip install requests`之后已经提示安装：
```
[root@centos-sg-1g shadowsocksr]# sudo pip install requests
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
执行`./tail.sh`
依然出错：
```
[root@centos-sg-1g shadowsocksr]# ./tail.sh
  File "/www/shadowsocksr/web_transfer.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
IPv6 support
Traceback (most recent call last):
  File "server.py", line 30, in <module>
    import web_transfer
  File "/www/shadowsocksr/web_transfer.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
