### ISSUE TITLE
默认下载的是dev版本

### ISSUE THREAD

**Issue by yigehaobb** [Ehco1996/shadowsocksr#5]
git clone https://github.com/Ehco1996/shadowsocksr.git 下载的是dev版本，cd scripts然后#初始化配置
bash initcfg.sh 提示 
chmod: cannot access ‘shadowsocks/*.sh’: No such file or directory
cp: cannot stat ‘apiconfig.py’: No such file or directory
cp: cannot stat ‘config.json’: No such file or directory
cp: cannot stat ‘mysql.json’: No such file or directory
 
下载master版本 改了toke和api 提示错误如下：

2018-04-19 00:26:53 ERROR    web_transfer.py:451 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 433, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/web_transfer.py", line 328, in pull_db_all_user
    nodeinfo = webapi.getApi('/nodes/{}'.format(node_id))
  File "/root/shadowsocksr/web_transfer.py", line 55, in getApi
    '网络问题，请保证api接口地址设置正确！当前接口地址：{}'.format(self.WEBAPI_URL))
Exception: 网络问题，请保证api接口地址设置正确！当前接口地址：http://127.0.0.1:8000/api

**Comment by Ehco1996** [comment]
dev分支 目前还不可用

需要自己 checkout  origin/master
